### ISSUE TITLE
Problems with wordpress (even installation of wordpress)

### ISSUE THREAD

**Issue by feanorknd** [OOPS-ORG-PHP/mod_execdir#26]
Hello....

When used extension along with wordpress (installing it), with PHP 7.4.15 (even php 7.3 and 7.2 last versions)...

`Fatal error: Cannot redeclare wp_get_server_protocol() (previously declared in herwise. */:1685339145) in /home/xxxx/public_html/test-php74/wp-includes/load.php on line 15`

Wordpress success first time... then the next requests to the same FPM thread will crash with the previous error.

Is this wonderful project active?

Regards and thanks!

**Comment by Joungkyun** [comment]
If you do not use mod_execdir, do you experience the same problem? The problem is that there is no reason to occur by mod_execdir.

If you are using OPCACHE, set it to opcache.fast_shutdown = 0 and try to run it.

I have not used WordPress, and after installing, let's make a confirmation of that issue.

**Comment by Joungkyun** [comment]
This issue has confirmed that it happens when used with **OPCACHE**.
Once you have confirmed the cause, but need more little time to solve the issue.

If opcache Disable, there is no problem. 

- Normal operation (check mark)
  - [x] PHP 7.0.33
  - [x] PHP 7.1.33
  - [x] PHP 7.2.34
  - [x] PHP 7.3.25, 7.3.27
  - [ ] PHP 7.4.16 - occur redeclare issue
  - [ ] PHP 8.0.3 - occur redeclare issue

**Comment by Joungkyun** [comment]
The cause is due to the preloading of opcache. The preloading function supports PHP 7.4 and after.
I am fixing this problem now.

**Comment by Joungkyun** [comment]
release 1.0.5

**Comment by feanorknd** [comment]
just forgot to say: thank you, thanks so much!
